# docker compose up --build --no-log-prefix
services:
  chat-completion:
    build: .
    environment:
      - MODEL_RUNNER_BASE_URL=${MODEL_RUNNER_BASE_URL}
      - MODEL_RUNNER_LLM_CHAT=${MODEL_RUNNER_LLM_CHAT}
      - MODEL_RUNNER_LLM_TOOLS=${MODEL_RUNNER_LLM_TOOLS}
    #depends_on:
    #  download-chat-llm:
    #    condition: service_completed_successfully

  # Download local LLMs

  download-chat-llm:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_LLM_CHAT}


  download-tools-llm:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_LLM_TOOLS}