# docker compose up --build --no-log-prefix
services:
  chat-completion:
    build: .
    environment:
      - MODEL_RUNNER_BASE_URL=${MODEL_RUNNER_BASE_URL}
      - MODEL_RUNNER_LLM_CHAT=${MODEL_RUNNER_LLM_CHAT}
      - MODEL_RUNNER_LLM_EMBEDDINGS=${MODEL_RUNNER_LLM_EMBEDDINGS}
    volumes:
      - ./docs:/docs


  download-chat-llm:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_LLM_CHAT}

  download-embeddings-llm:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_LLM_EMBEDDINGS}

  redis-server:
    image: redis:8.0.0-alpine3.21
    environment: 
      - REDIS_ARGS=--save 30 1
      # snapshot
    ports:
      - 6379:6379
    volumes:
      - ./data:/data


  stop-redis:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/sh
      - -c
      - |  
        # Stopping Redis...
        docker stop 02-rag-redis-server-1 > /dev/null
      
    depends_on:
      chat-completion:
        condition: service_completed_successfully      